export let projectsData = [
  {
    id: 2,
    title: "SocialNet",
    description: "Portfolio page",
    categories: ["HTML", "CSS", "JS", "REACT", "NextJs", "NextAuth", "MONGODB"],
    image: "SocialNet.png",
    srcUrl: "https://github.com/Adelinked",
  },
  {
    id: 3,
    title: "Portfolio HTML page",
    description: "Portfolio page: A simple html portfolio page.",
    categories: ["HTML", "CSS"],
    image: "portfolio_page.png",
    srcUrl: "https://github.com/Adelinked/portfolio-project",
    depUrl: "https://adelinked.github.io/portfolio-project/",
  },
  {
    id: 4,
    title: "Js calculator",
    description: "Js calculator",
    categories: ["HTML", "CSS", "JS", "React"],
    image: "calculator.png",
    srcUrl: "https://github.com/Adelinked/Js-calculator",
    depUrl: "https://adelinked.github.io/Js-calculator/",
  },
  {
    id: 1,
    title: "E-commerce",
    description: "E-commerce E-commerce E-commerce E-commerce",
    categories: ["HTML", "CSS", "JS", "React", "NextJs", "Redux", "NextAuth"],
    image: "https://i.postimg.cc/7YVxtsXp/products.png",
    srcUrl: "https://github.com/Adelinked/E-commerce",
    depUrl: "https://e-commerce-adelinked.netlify.app/",
    demoUrl: "",
  },
  {
    id: 5,
    title: "Music-Albums",
    description: " An application to display albums of a given artist",
    categories: ["HTML", "CSS", "JS", "React", "NextJs"],
    image: "musicApp.png",
    srcUrl: "https://github.com/Adelinked/Music-albums",
    depUrl: "https://music-albums-adelinked.netlify.app/",
    demoUrl: "",
  },
  {
    id: 6,
    title: "Weather forcast",
    description:
      " An application for weather forcast in your city and other cities",
    categories: ["HTML", "CSS", "JS", "React", "NextJs"],
    image: "weatherForcast.png",
    srcUrl: "https://github.com/Adelinked/weather-forcast",
    depUrl: "https://weather-forcast-adelinked.netlify.app/",
    demoUrl: "",
  },
  {
    id: 7,
    title: "Quiz App",
    description: "Quiz app made using NextJs framework and Redux Thunk",
    categories: ["HTML", "CSS", "JS", "React", "NextJs", "Redux"],
    image: "quizApp.png",
    srcUrl: "https://github.com/Adelinked/Quiz-app-redux",
    depUrl: "https://quiz-app-redux-adelinked.netlify.app",
    demoUrl: "",
  },
  {
    id: 8,
    title: "Hacker News Search",
    description: "Hacker news search",
    categories: ["HTML", "CSS", "JS", "React", "NextJs"],
    image: "hackerNews.png",
    srcUrl: "https://github.com/Adelinked/hacker-news-search",
    depUrl: "https://hacker-news-adelinked.netlify.app/",
    demoUrl: "",
  },
  {
    id: 9,
    title: "Photos App",
    description:
      "An application to display photos using unsplash-api as a source of data ",
    categories: ["HTML", "CSS", "JS", "React", "NextJs"],
    image: "photosApp.png",
    srcUrl: "https://github.com/Adelinked/Photos-app",
    depUrl: "https://photos-app-adelinked.netlify.app/",
    demoUrl: "",
  },
  {
    id: 10,
    title: "Shopping cart ",
    description: "Cart using useState hook vs Redux ",
    categories: [
      "HTML",
      "CSS",
      "JS",
      "React",
      "NextJs",
      "Redux",
      "TS",
      "Jest",
      "CI",
    ],
    image: "cart.png",
    srcUrl: "https://github.com/Adelinked/CartTypeScript",
    srcUrl2: "https://github.com/Adelinked/Cart",
    depUrl: "https://cart-usestate-redux-typescript.netlify.app/",
    depUrl2: "https://shopping-cart-adelinked.netlify.app/",
    demoUrl: "",
  },
  {
    id: 11,
    title: "Dark mode",
    description: " Dark mode with react ",
    categories: ["HTML", "CSS", "JS", "React", "NextJs"],
    image: "darkMode.png",
    srcUrl: "https://github.com/Adelinked/Dark-mode",
    depUrl: "https://dark-mode-adelinked.netlify.app/",
    demoUrl: "",
  },
  {
    id: 12,
    title: "25 + 5 Clock",
    description:
      "Pomodoro 25+5 clock using React class components made during FreeCodeCamp courses",
    categories: ["HTML", "CSS", "JS", "React"],
    image: "pomodoro.png",
    srcUrl: "https://github.com/Adelinked/Pomodoro",
    depUrl: "https://adelinked.github.io/Pomodoro/",
    demoUrl: "",
  },
];

export let skillsData = [
  { num: 1, title: "JavaScript", image: "languages/js.png" },
  { num: 2, title: "HTML", image: "languages/html.png" },
  { num: 3, title: "CSS", image: "languages/css.png" },
  { num: 4, title: "React", image: "languages/react.png" },
  { num: 5, title: "NextJs", image: "languages/NextJs.png" },
  { num: 6, title: "Redux", image: "languages/redux.png" },
  { num: 7, title: "Node", image: "languages/nodejs.png" },
  { num: 8, title: "Mongodb", image: "languages/mongodb.png" },
  { num: 9, title: "TypeScript", image: "languages/typescript.png" },
  { num: 10, title: "Jest", image: "languages/jest.png" },
];
